-- ============================================================================
--  El Almacén — Esquema Supabase (PostgreSQL)
--  Generado desde la app. Pegar en: Supabase → SQL Editor → Run.
--  Incluye: tablas, índices, RLS, función crear_pedido() y datos de ejemplo.
-- ============================================================================

create extension if not exists pgcrypto;

-- ---------- limpieza (por si re-ejecutás) ----------
drop function if exists crear_pedido(text,text,text,text,text,text,jsonb);
drop table if exists pedido_items, pedidos, promo_items, promos, productos,
  categorias, formas_pago, tipos_envio, estados_pedido, clientes, usuarios, config cascade;

-- ============================ CONFIG (fila única) ============================
create table config (
  id             int primary key default 1 check (id = 1),
  nombre         text not null default 'El Almacén',
  marca          text default 'A',
  sub            text,
  hero_titulo    text,
  hero_texto     text,
  hero_tags      jsonb default '[]'::jsonb,
  logo           text default '',
  cerrado_manual boolean default false,
  horarios       jsonb default '[]'::jsonb,   -- [{d,abierto,desde,hasta}]
  ui             jsonb default '{}'::jsonb,    -- ajustes de diseño
  updated_at     timestamptz default now()
);

-- ============================ CATÁLOGOS =====================================
create table categorias (
  id text primary key, nombre text not null, emoji text, color text, orden int default 0
);
create table formas_pago (
  id text primary key, nombre text not null, emoji text, orden int default 0
);
create table tipos_envio (
  id text primary key, nombre text not null, descripcion text,
  costo numeric(12,2) default 0, emoji text, pide_dir boolean default false, orden int default 0
);
create table estados_pedido (
  id text primary key, nombre text not null, color text, orden int default 0
);

-- ============================ PRODUCTOS =====================================
create table productos (
  id           text primary key,
  nombre       text not null,
  categoria_id text references categorias(id) on delete set null,
  precio       numeric(12,2) not null default 0,
  unidad       text not null default 'un' check (unidad in ('kg','un','doc')),
  emoji        text,
  descripcion  text,
  activo       boolean default true,
  orden        int default 0,
  created_at   timestamptz default now()
);
create index idx_productos_cat on productos(categoria_id);
create index idx_productos_activo on productos(activo);

-- ============================ PROMOS ========================================
create table promos (
  id text primary key, nombre text not null, emoji text, descripcion text,
  precio numeric(12,2) not null default 0, activo boolean default true, orden int default 0
);
create table promo_items (
  promo_id    text references promos(id) on delete cascade,
  producto_id text references productos(id) on delete cascade,
  cantidad    numeric(12,3) not null default 1,
  primary key (promo_id, producto_id)
);

-- ============================ CLIENTES ======================================
create table clientes (
  id         text primary key default gen_random_uuid()::text,
  nombre     text not null,
  tel        text,
  dir        text,
  email      text,
  nota       text,
  created_at timestamptz default now()
);
create index idx_clientes_tel on clientes(tel);

-- ============================ USUARIOS DEL PANEL ============================
-- NOTA: para producción real conviene Supabase Auth (ver README). Esta tabla
-- replica el login simple de la app (demo). La contraseña NO debería quedar
-- en texto plano en un sistema real.
create table usuarios (
  id         text primary key default gen_random_uuid()::text,
  usuario    text unique not null,
  pass       text not null,
  nombre     text,
  rol        text not null default 'cliente' check (rol in ('admin','empleado','cliente')),
  tel        text,
  created_at timestamptz default now()
);

-- ============================ PEDIDOS =======================================
create table pedidos (
  n              bigint generated by default as identity primary key,
  ts             timestamptz default now(),
  cliente_nombre text,
  cliente_tel    text,
  cliente_dir    text,
  tipo           text references tipos_envio(id),
  pago           text references formas_pago(id),
  estado         text references estados_pedido(id),
  nota           text,
  envio_costo    numeric(12,2) default 0,
  total          numeric(12,2) default 0
);
create index idx_pedidos_estado on pedidos(estado);
create index idx_pedidos_tel on pedidos(cliente_tel);
create index idx_pedidos_ts on pedidos(ts desc);

create table pedido_items (
  id          bigint generated by default as identity primary key,
  pedido_n    bigint references pedidos(n) on delete cascade,
  producto_id text,                 -- id de producto o de promo (referencia suave)
  nombre      text not null,        -- snapshot al momento del pedido
  unidad      text default 'un',
  precio      numeric(12,2) not null,
  qty         numeric(12,3) not null,
  es_promo    boolean default false
);
create index idx_pitems_pedido on pedido_items(pedido_n);

-- ============================ updated_at (config) ===========================
create or replace function touch_updated_at() returns trigger language plpgsql as $$
begin new.updated_at = now(); return new; end $$;
create trigger trg_config_updated before update on config
  for each row execute function touch_updated_at();

-- ============================================================================
--  RPC: crear_pedido  (para que la tienda pública cree pedidos de forma segura,
--  sin exponer las tablas de pedidos/clientes a escritura anónima directa)
-- ============================================================================
create or replace function crear_pedido(
  p_nombre text, p_tel text, p_dir text,
  p_tipo text, p_pago text, p_nota text,
  p_items jsonb           -- [{producto_id,nombre,unidad,precio,qty,es_promo}]
) returns bigint
language plpgsql security definer set search_path = public as $$
declare
  v_n bigint; v_estado text; v_envio numeric := 0; v_total numeric := 0; it jsonb;
begin
  if p_items is null or jsonb_array_length(p_items) = 0 then
    raise exception 'El pedido no tiene items';
  end if;
  select id into v_estado from estados_pedido order by orden asc, id asc limit 1;
  select coalesce(costo,0) into v_envio from tipos_envio where id = p_tipo;
  select coalesce(sum((i->>'precio')::numeric * (i->>'qty')::numeric),0)
    into v_total from jsonb_array_elements(p_items) i;
  v_total := v_total + coalesce(v_envio,0);

  insert into pedidos(cliente_nombre,cliente_tel,cliente_dir,tipo,pago,estado,nota,envio_costo,total)
  values (p_nombre,p_tel,p_dir,p_tipo,p_pago,v_estado,p_nota,coalesce(v_envio,0),v_total)
  returning n into v_n;

  for it in select * from jsonb_array_elements(p_items) loop
    insert into pedido_items(pedido_n,producto_id,nombre,unidad,precio,qty,es_promo)
    values (v_n, it->>'producto_id', it->>'nombre', coalesce(it->>'unidad','un'),
            (it->>'precio')::numeric, (it->>'qty')::numeric,
            coalesce((it->>'es_promo')::boolean,false));
  end loop;

  if p_tel is not null and length(trim(p_tel)) > 0 then
    if exists (select 1 from clientes where tel = p_tel) then
      update clientes set nombre = coalesce(nullif(p_nombre,''), nombre),
                          dir    = coalesce(nullif(p_dir,''), dir)
        where tel = p_tel;
    else
      insert into clientes(nombre,tel,dir) values (p_nombre,p_tel,p_dir);
    end if;
  end if;
  return v_n;
end $$;

-- ============================================================================
--  RLS (Row Level Security)
--  Público (anon): lee catálogo/config y crea pedidos SOLO vía crear_pedido().
--  Staff (authenticated, vía Supabase Auth): gestiona todo.
-- ============================================================================
alter table config          enable row level security;
alter table categorias      enable row level security;
alter table formas_pago     enable row level security;
alter table tipos_envio     enable row level security;
alter table estados_pedido  enable row level security;
alter table productos       enable row level security;
alter table promos          enable row level security;
alter table promo_items     enable row level security;
alter table clientes        enable row level security;
alter table usuarios        enable row level security;
alter table pedidos         enable row level security;
alter table pedido_items    enable row level security;

-- Lectura pública del escaparate
create policy leer_config     on config         for select using (true);
create policy leer_categorias on categorias     for select using (true);
create policy leer_pagos      on formas_pago    for select using (true);
create policy leer_envios     on tipos_envio    for select using (true);
create policy leer_estados    on estados_pedido for select using (true);
create policy leer_productos  on productos      for select using (true);
create policy leer_promos     on promos         for select using (true);
create policy leer_promoitems on promo_items    for select using (true);

-- Gestión total para usuarios autenticados (staff)
create policy admin_config     on config         for all to authenticated using (true) with check (true);
create policy admin_categorias on categorias     for all to authenticated using (true) with check (true);
create policy admin_pagos      on formas_pago    for all to authenticated using (true) with check (true);
create policy admin_envios     on tipos_envio    for all to authenticated using (true) with check (true);
create policy admin_estados    on estados_pedido for all to authenticated using (true) with check (true);
create policy admin_productos  on productos      for all to authenticated using (true) with check (true);
create policy admin_promos     on promos         for all to authenticated using (true) with check (true);
create policy admin_promoitems on promo_items    for all to authenticated using (true) with check (true);
create policy admin_clientes   on clientes       for all to authenticated using (true) with check (true);
create policy admin_usuarios   on usuarios       for all to authenticated using (true) with check (true);
create policy admin_pedidos    on pedidos        for all to authenticated using (true) with check (true);
create policy admin_pitems     on pedido_items   for all to authenticated using (true) with check (true);

-- La tienda pública crea pedidos únicamente por la función (SECURITY DEFINER)
revoke all on function crear_pedido(text,text,text,text,text,text,jsonb) from public;
grant execute on function crear_pedido(text,text,text,text,text,text,jsonb) to anon, authenticated;

-- ============================================================================
--  DATOS DE EJEMPLO (extraídos de la app)
-- ============================================================================

insert into config(id,nombre,marca,sub,hero_titulo,hero_texto,hero_tags,logo,cerrado_manual,horarios,ui) values
(1, 'El Almacén', 'A', 'Fiambrería · Panadería · Carnicería · Heladería', 'Hacé tu compra del barrio y te la llevamos a casa', 'Fiambres cortados al momento, pan del día, carne fresca, almacén, limpieza y helado. Pedí, elegí take away o envío, y pagá como quieras.', '["🛵 Envío a domicilio","🥪 Take away","💳 Efectivo, transferencia o Mercado Pago"]'::jsonb, '', false, '[]'::jsonb, '{}'::jsonb);

insert into categorias(id,nombre,emoji,color,orden) values
  ('fiambreria', 'Fiambrería', '🧀', '#FBEFD3', 0),
  ('almacen', 'Almacén', '🥫', '#E7EFE9', 1),
  ('limpieza', 'Limpieza', '🧴', '#E3EEF6', 2),
  ('panaderia', 'Panadería', '🥖', '#F6E9D6', 3),
  ('carniceria', 'Carnicería', '🥩', '#F6E3E0', 4),
  ('heladeria', 'Heladería', '🍦', '#F0E6F6', 5);

insert into formas_pago(id,nombre,emoji,orden) values
  ('efectivo', 'Efectivo', '💵', 0),
  ('transferencia', 'Transferencia', '🏦', 1),
  ('mercadopago', 'Mercado Pago', '💙', 2),
  ('tarjeta', 'Tarjeta', '💳', 3);

insert into tipos_envio(id,nombre,descripcion,costo,emoji,pide_dir,orden) values
  ('takeaway', 'Take away', 'Lo retirás vos', 0, '🥪', false, 0),
  ('delivery', 'Envío', 'A domicilio', 1500, '🛵', true, 1);

insert into estados_pedido(id,nombre,color,orden) values
  ('pendiente', 'Pendiente', '#E0A32B', 0),
  ('preparacion', 'En preparación', '#2E6FB0', 1),
  ('listo', 'Listo', '#1E4D3A', 2),
  ('entregado', 'Entregado', '#6B6459', 3),
  ('cancelado', 'Cancelado', '#C23B2E', 99);

insert into productos(id,nombre,categoria_id,precio,unidad,emoji,descripcion,activo,orden) values
  ('p01', 'Jamón cocido natural', 'fiambreria', 12800, 'kg', '🍖', 'Cortado en el momento, tajada fina o gruesa.', true, 0),
  ('p02', 'Jamón crudo', 'fiambreria', 24500, 'kg', '🥓', 'Estacionado, ideal picada.', true, 1),
  ('p03', 'Salame Milán', 'fiambreria', 15900, 'kg', '🌭', 'Sabor intenso, corte fino.', true, 2),
  ('p04', 'Mortadela', 'fiambreria', 8900, 'kg', '🍥', 'Clásica con pistacho.', true, 3),
  ('p05', 'Queso cremoso', 'fiambreria', 11200, 'kg', '🧀', 'Fresco, para sándwich o tabla.', true, 4),
  ('p06', 'Queso provolone', 'fiambreria', 16800, 'kg', '🧀', 'Para provoleta a la parrilla.', true, 5),
  ('p07', 'Queso rallado 250g', 'fiambreria', 3200, 'un', '🧀', 'Reggianito rallado fresco.', true, 6),
  ('p08', 'Bondiola cocida', 'fiambreria', 21000, 'kg', '🍖', 'Ahumada, en tajadas.', true, 7),
  ('p09', 'Fideos guiseros 500g', 'almacen', 1400, 'un', '🍝', 'Tirabuzón o mostachol.', true, 8),
  ('p10', 'Arroz largo fino 1kg', 'almacen', 2100, 'un', '🍚', 'Grano suelto, no se pega.', true, 9),
  ('p11', 'Aceite girasol 1,5L', 'almacen', 3800, 'un', '🫗', 'Para cocina y frituras.', true, 10),
  ('p12', 'Puré de tomate 520g', 'almacen', 1250, 'un', '🥫', 'Triple concentrado.', true, 11),
  ('p13', 'Yerba mate 1kg', 'almacen', 5600, 'un', '🧉', 'Con palo, suave.', true, 12),
  ('p14', 'Azúcar 1kg', 'almacen', 1600, 'un', '🍬', 'Refinada.', true, 13),
  ('p15', 'Harina 000 1kg', 'almacen', 1300, 'un', '🌾', 'Para pan y pizza.', true, 14),
  ('p16', 'Café molido 500g', 'almacen', 7800, 'un', '☕', 'Torrado, aroma intenso.', true, 15),
  ('p17', 'Gaseosa 2,25L', 'almacen', 3500, 'un', '🥤', 'Cola bien fría.', true, 16),
  ('p18', 'Lavandina 1L', 'limpieza', 1200, 'un', '🧴', 'Concentrada, desinfecta.', true, 17),
  ('p19', 'Detergente 750ml', 'limpieza', 2400, 'un', '🧼', 'Rinde el doble.', true, 18),
  ('p20', 'Jabón en polvo 800g', 'limpieza', 4200, 'un', '🧺', 'Para lavarropas.', true, 19),
  ('p21', 'Papel higiénico x4', 'limpieza', 3600, 'un', '🧻', 'Doble hoja.', true, 20),
  ('p22', 'Rollo de cocina x3', 'limpieza', 3900, 'un', '🧻', 'Súper absorbente.', true, 21),
  ('p23', 'Esponjas x3', 'limpieza', 1500, 'un', '🧽', 'Doble faz.', true, 22),
  ('p24', 'Pan flauta', 'panaderia', 1400, 'un', '🥖', 'Recién horneado.', true, 23),
  ('p25', 'Facturas (docena)', 'panaderia', 6500, 'doc', '🥐', 'Surtidas, del día.', true, 24),
  ('p26', 'Prepizza x2', 'panaderia', 2800, 'un', '🍕', 'Con salsa lista.', true, 25),
  ('p27', 'Pan de salvado', 'panaderia', 1900, 'un', '🍞', 'Integral, con semillas.', true, 26),
  ('p28', 'Medialunas (docena)', 'panaderia', 7200, 'doc', '🥐', 'De manteca, dulces.', true, 27),
  ('p29', 'Carne picada especial', 'carniceria', 9800, 'kg', '🥩', 'Magra, picada al momento.', true, 28),
  ('p30', 'Milanesas de nalga', 'carniceria', 13500, 'kg', '🍖', 'Finitas, ya empanadas.', true, 29),
  ('p31', 'Pollo entero', 'carniceria', 4200, 'kg', '🍗', 'Fresco, de granja.', true, 30),
  ('p32', 'Bife de chorizo', 'carniceria', 16900, 'kg', '🥩', 'Cortes gruesos para parrilla.', true, 31),
  ('p33', 'Matambre', 'carniceria', 12800, 'kg', '🥩', 'Para pizza o a la parrilla.', true, 32),
  ('p34', 'Chorizo parrillero', 'carniceria', 8600, 'kg', '🌭', 'Puro, sin conservantes.', true, 33),
  ('p35', 'Helado 1kg (elegís 3 gustos)', 'heladeria', 9500, 'un', '🍨', 'Aclará los gustos en la nota.', true, 34),
  ('p36', 'Helado 1/4 kg', 'heladeria', 3200, 'un', '🍦', 'Dos gustos.', true, 35),
  ('p37', 'Palitos bombón x6', 'heladeria', 4800, 'un', '🍫', 'Bañados en chocolate.', true, 36),
  ('p38', 'Cucurucho', 'heladeria', 2200, 'un', '🍦', 'Un gusto a elección.', true, 37);

insert into promos(id,nombre,emoji,descripcion,precio,activo,orden) values
  ('promo1', 'Combo Picada', '🧀', 'Todo para la picada del finde.', 13900, true, 0),
  ('promo2', 'Combo Asado', '🥩', 'Listo para la parrilla.', 26900, true, 1),
  ('promo3', 'Combo Desayuno', '🥐', 'Medialunas, café y yerba.', 17900, true, 2);

insert into promo_items(promo_id,producto_id,cantidad) values
  ('promo1', 'p02', 0.25),
  ('promo1', 'p03', 0.25),
  ('promo1', 'p05', 0.25),
  ('promo1', 'p24', 2),
  ('promo2', 'p32', 1),
  ('promo2', 'p34', 0.5),
  ('promo2', 'p24', 2),
  ('promo2', 'p17', 2),
  ('promo3', 'p28', 1),
  ('promo3', 'p16', 1),
  ('promo3', 'p13', 1);

insert into clientes(id,nombre,tel,dir,email,nota) values
  ('c1', 'Marta Gómez', '1145550011', 'Belgrano 240', '', 'Pide jamón en tajada fina'),
  ('c2', 'Jorge Díaz', '1145550022', '', '', ''),
  ('c3', 'Lucía Fernández', '1145550033', 'San Martín 1180', '', 'Timbre 2B'),
  ('c4', 'Roberto Páez', '1145550044', '', '', ''),
  ('c5', 'Ana Suárez', '1145550055', 'Rivadavia 55', '', '');

insert into usuarios(id,usuario,pass,nombre,rol,tel) values
  ('u1', 'admin', 'admin', 'Dueño/a', 'admin', ''),
  ('u2', 'cliente', 'cliente', 'Marta Gómez', 'cliente', '1145550011');

-- Fin. Pedidos: se cargan en producción (o vía crear_pedido()).
